Task 2
SamoylenkVi/cinema-project pull request #2
Opened 2022-12-04 10:10 UTC by SamoylenkVi

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/main.js
> +const filmCards = new Array(FILM_COUNT).fill().map((element, idElement) => generateCardFilm(idElement));
Можно избавиться от комментария `// eslint-disable-next-line max-len` если по другому написать код? 
```suggestion
const filmCards = new Array(FILM_COUNT)
    .fill()
    .map((element, idElement) => generateCardFilm(idElement));
```

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/main.js
> +render(mainElement, createMenuTempale(filmCards), 'beforeend');
Опечатка? createMenuTempale --> createMenuTemplate

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/mock/card-film.js
> +  const productionYear = [
Можно вынести из функции чтобы при каждом вызове не генерировать

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/mock/filter.js
> +  return result.length;
Переменная result может содержать undefined?

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/utils.js
> +  // eslint-disable-next-line no-param-reassign
Удали коммент и перепиши код: плохая практика переопределять параметры функции.
Вместо это объяви внутри переменную в которую положи результат `text.trim()`

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/utils.js
> +  // eslint-disable-next-line no-param-reassign
И этот тоже

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/utils.js
> +    text.substr(0, lastSpace);
Что тут происходит и как это работает?)

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/utils.js
> +  render, getRandomInteger, cutText, addActiveButtonClass,
```suggestion
  render,
  getRandomInteger,
  cutText,
  addActiveButtonClass,
```

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/view/ movie-card.js
> +  // const filmComment = createComment(commentId, allComments);
Забыла удалить?

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/view/ movie-card.js
> +  <a class="film-card__comments"> ${allComments[commentId].length} comments</a>
вынеси в переменную `allComments[commentId].length` - будет проще читать

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/utils.js
> +const addActiveButtonClass = (button, className) => (button ? className : '');
`button` - булевое значение? Тогда лучше переименовать, например, на isActive

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/view/film-details.js
> +          <span class="film-details__comment-day">${dayjs(commentDate).format('YYYY/MM/DD HH:m')}</span>
`dayjs(commentDate).format('YYYY/MM/DD HH:m')` в отдельную переменную, а `YYYY/MM/DD HH:m` в константу

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/view/film-details.js
> +                <td class="film-details__cell">${dayjs(productionYear).format('DD MMMM YYYY')}</td>
тоже вынести бы, чтобы проще было читать

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/view/film-details.js
> +          <h3 class="film-details__comments-title">Comments <span class="film-details__comments-count">${allComments[commentId].length}</span></h3>
в переменную

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/view/menu.js
> +  const filterMarkup = filters.map((filter) => {
```suggestion
  const filterMarkup = filters.map(({ name, count }) => `<a href="#${name}" class="main-navigation__item">${name} <span class="main-navigation__item-count">${count}</span></a>`
```

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/mock/film-comments.js
> +  for (let i = 0; i < COMMENTS_COUNT; i++) {
```suggestion
  for (let cardId = 0; cardId < COMMENTS_COUNT; cardId++) {
```

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/mock/card-film.js
> +  commentId: id,
```suggestion
  id,
```
И вынеси это поле на первое место

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/mock/film-comments.js
> +const COMMENTS_COUNT = 20;
Это не COMMENTS_COUNT, а CARD_COUNT ? Верно?

2022-12-04 10:51 UTC, Pavel-Liteiniy commented on src/mock/film-comments.js
> +  const commentCount = getRandomInteger(0, 10);
В условии к задаче написано от 0 до 5?
Тогда нужно поправить + вынести в константу это значение

2022-12-06 19:06 UTC, Pavel-Liteiniy commented on src/mock/filter.js
> +  return result.length;
Не актуально. Пустой массив будет в любом случае

2022-12-06 19:13 UTC, SamoylenkVi commented on src/main.js
> +const filmCards = new Array(FILM_COUNT).fill().map((element, idElement) => generateCardFilm(idElement));
fixed

2022-12-06 19:13 UTC, SamoylenkVi commented on src/main.js
> +render(mainElement, createMenuTempale(filmCards), 'beforeend');
fixed

2022-12-06 19:14 UTC, SamoylenkVi commented on src/utils.js
> +  // eslint-disable-next-line no-param-reassign
fixed

2022-12-06 19:14 UTC, SamoylenkVi commented on src/utils.js
> +  // eslint-disable-next-line no-param-reassign
fixed

2022-12-06 19:14 UTC, SamoylenkVi commented on src/utils.js
> +    text.substr(0, lastSpace);
fixed

2022-12-06 19:15 UTC, SamoylenkVi commented on src/utils.js
> +  render, getRandomInteger, cutText, addActiveButtonClass,
fixed

2022-12-06 19:16 UTC, SamoylenkVi commented on src/view/ movie-card.js
> +  // const filmComment = createComment(commentId, allComments);
fixed

2022-12-06 19:18 UTC, SamoylenkVi commented on src/view/ movie-card.js
> +  <a class="film-card__comments"> ${allComments[commentId].length} comments</a>
fixed

2022-12-06 19:22 UTC, SamoylenkVi commented on src/utils.js
> +const addActiveButtonClass = (button, className) => (button ? className : '');
fixed

2022-12-06 19:44 UTC, SamoylenkVi commented on src/view/film-details.js
> +          <span class="film-details__comment-day">${dayjs(commentDate).format('YYYY/MM/DD HH:m')}</span>
fixed

2022-12-06 19:44 UTC, SamoylenkVi commented on src/view/film-details.js
> +                <td class="film-details__cell">${dayjs(productionYear).format('DD MMMM YYYY')}</td>
fixed

2022-12-06 19:46 UTC, SamoylenkVi commented on src/view/film-details.js
> +          <h3 class="film-details__comments-title">Comments <span class="film-details__comments-count">${allComments[commentId].length}</span></h3>
fixed

2022-12-06 19:47 UTC, SamoylenkVi commented on src/view/menu.js
> +  const filterMarkup = filters.map((filter) => {
fixed

2022-12-06 19:47 UTC, SamoylenkVi commented on src/mock/film-comments.js
> +  for (let i = 0; i < COMMENTS_COUNT; i++) {
fixed

2022-12-06 19:47 UTC, SamoylenkVi commented on src/mock/card-film.js
> +  commentId: id,
fixed

2022-12-06 19:48 UTC, SamoylenkVi commented on src/mock/film-comments.js
> +const COMMENTS_COUNT = 20;
fixed

2022-12-06 19:48 UTC, SamoylenkVi commented on src/mock/film-comments.js
> +  const commentCount = getRandomInteger(0, 10);
fixed

2022-12-06 20:12 UTC, Pavel-Liteiniy commented on src/view/film-details.js
> +  const GenreMarkup = items.map((item) => `<span class="film-details__genre">${item}</span>`);
Почему название переменной начинается с заглавной буквы `GenreMarkup`?

2022-12-06 20:20 UTC, SamoylenkVi commented on src/view/film-details.js
> +  const GenreMarkup = items.map((item) => `<span class="film-details__genre">${item}</span>`);
fixed

2022-12-06 20:24 UTC, Pavel-Liteiniy commented on src/view/film-details.js
> +  const GenreMarkup = items.map((item) => `<span class="film-details__genre">${item}</span>`);
/ok

2022-12-06 20:31 UTC, Pavel-Liteiniy requested changes

2022-12-06 20:31 UTC, Pavel-Liteiniy commented on package.json
>      "node": "12"
Opa na!

2022-12-07 16:11 UTC, merged